Added validation check on inputs

diff --git a/.github/actions/deploy/vercel/development/action.yml b/.github/actions/deploy/vercel/development/action.yml
--- a/.github/actions/deploy/vercel/development/action.yml
+++ b/.github/actions/deploy/vercel/development/action.yml
@@ -23,6 +23,14 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check required inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.vercel-token }}" ] || [ -z "${{ inputs.vercel-org-id }}" ] || [ -z "${{ inputs.vercel-project-id }}" ]; then
+          echo "Error: Required inputs are not available."
+          exit 1
+        fi
+
     - name: Install Vercel CLI
       shell: bash
       run: npm install --global vercel@latest
diff --git a/.github/actions/generate-app-id/action.yml b/.github/actions/generate-app-id/action.yml
--- a/.github/actions/generate-app-id/action.yml
+++ b/.github/actions/generate-app-id/action.yml
@@ -48,6 +48,14 @@ runs:
           exit 1
         fi
 
+    - name: Check required inputs
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.deriv_api_token }}" ] || [ -z "${{ inputs.github_token }}" ]; then
+          echo "Error: Required inputs are not available."
+          exit 1
+        fi
+
     - name: Generate Deriv App ID
       id: generate_app_id
       uses: deriv-com/deriv-app-id-action@v1
